controller_manager:
  ros__parameters:
    update_rate: 30
    
    use_sim_time: true
    
    asc:
        type: ackermann_steering_controller/AckermannSteeringController       
    
    jsc:
      type: joint_state_broadcaster/JointStateBroadcaster
    
asc:
  ros__parameters:
    publish_rate: 30.0
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    rear_wheels_names: [rear_right_joint, rear_left_joint]
    front_wheels_names: [front_right_hinge_joint, front_left_hinge_joint]


    wheelbase: 0.35
    front_wheel_track: 0.242
    rear_wheel_track: 0.242
    front_wheels_radius: 0.033
    rear_wheels_radius: 0.033
    
    
#jsc:
#  ros__parameters:
#    type: joint_state_controller/JointStateController

